# Generated by Django 3.1b1 on 2020-06-28 16:12

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('guid', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=9)),
                ('avatar', models.URLField(blank=True)),
                ('year', models.CharField(blank=True, choices=[(73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109)], default=109, max_length=3)),
                ('name', models.CharField(max_length=31)),
                ('foreign_name', models.CharField(blank=True, max_length=31, null=True)),
                ('hobby', models.CharField(max_length=127)),
                ('expertise', models.CharField(max_length=127)),
                ('constellation', models.CharField(max_length=31)),
                ('link', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('education', models.CharField(choices=[('Master', 'Master'), ('Ph.D.', 'Ph.D.'), ('EMBA', 'EMBA'), ('EDBA', 'EDBA'), ('Professor', 'Professor')], default='Master', max_length=15)),
                ('is_graduated', models.BooleanField(choices=[(True, True), (False, False)], default=False)),
            ],
            bases=(common.models.BaseSheet, models.Model),
        ),
    ]
